// <auto-generated />
using System;
using ChatbotClient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatbotClient.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("ChatbotClient.Models.AiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AiModels");
                });

            modelBuilder.Entity("ChatbotClient.Models.SessionFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentFolderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessionFolders");
                });

            modelBuilder.Entity("ChatbotClient.Models.SystemPromptEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemPrompts");
                });

            modelBuilder.Entity("ChatbotClient.Models.TalkEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AiModelId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AiModelType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SystemPromptGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TalkSessionGuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SystemPromptGuid");

                    b.HasIndex("TalkSessionGuid");

                    b.ToTable("TalkEntries");
                });

            modelBuilder.Entity("ChatbotClient.Models.TalkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("TalkSessions");
                });

            modelBuilder.Entity("ChatbotClient.Models.TalkEntry", b =>
                {
                    b.HasOne("ChatbotClient.Models.SystemPromptEntry", "SystemPrompt")
                        .WithMany()
                        .HasForeignKey("SystemPromptGuid")
                        .HasPrincipalKey("Guid");

                    b.HasOne("ChatbotClient.Models.TalkSession", "TalkSession")
                        .WithMany("Entries")
                        .HasForeignKey("TalkSessionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemPrompt");

                    b.Navigation("TalkSession");
                });

            modelBuilder.Entity("ChatbotClient.Models.TalkSession", b =>
                {
                    b.HasOne("ChatbotClient.Models.SessionFolder", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderId");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("ChatbotClient.Models.TalkSession", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
